---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      flowtype-errors/show-errors:
        enabled: false
      flowtype-errors/enforce-min-coverage:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- node_modules
- private/__mocks__
- private/semantic
- public/
- flow-typed/
- coverage/
- .next/
- .out/
